insert into product_pricing(product_catalog_entity_product_id, cost_per_product, cost_unit) values (101, 15, 30)
insert into product_pricing(product_catalog_entity_product_id, cost_per_product, cost_unit) values (102, 20, 60)
insert into product_pricing(product_catalog_entity_product_id, cost_per_product, cost_unit) values (103, 25, 100)
insert into product_pricing(product_catalog_entity_product_id, cost_per_product, cost_unit) values (104, 30, 120)
insert into product_pricing(product_catalog_entity_product_id, cost_per_product, cost_unit) values (105, 35, 140)